### ISSUE TITLE
HardhatError: HH109: Network connection timed-out

### ISSUE THREAD

**Issue by bafu** [aurora-is-near/aurora-examples#47]
Following [this Hardhat tutoria](https://doc.aurora.dev/interact/hardhat) and got a timeout error below:

```
aurora-examples/hardhat/erc20 $ make deploy NETWORK=testnet_aurora
yarn hardhat run scripts/deploy.js --network testnet_aurora
yarn run v1.22.5
$ aurora-examples/hardhat/erc20/node_modules/.bin/hardhat run scripts/deploy.js --network testnet_aurora
Downloading compiler 0.8.0
Compiling 5 files with 0.8.0
Compilation finished successfully
Deploying contracts with the account: 0x63B7076FC0A914Af543C2e5c201df6C29FCC18c5
Account balance: 441776510000000
HardhatError: HH109: Network connection timed-out.
Please check your internet connection and networks config
    at HttpProvider._fetchJsonRpcResponse (/home/bafu/codes/evm-survey/aurora-evm-survey/aurora-examples/hardhat/erc20/node_modules/hardhat/src/internal/core/providers/http.ts:175:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HttpProvider.request (/home/bafu/codes/evm-survey/aurora-evm-survey/aurora-examples/hardhat/erc20/node_modules/hardhat/src/internal/core/providers/http.ts:52:29)
    at EthersProviderWrapper.send (/home/bafu/codes/evm-survey/aurora-evm-survey/aurora-examples/hardhat/erc20/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

    Caused by: FetchError: network timeout at: https://testnet.aurora.dev/
        at Timeout.<anonymous> (/home/bafu/codes/evm-survey/aurora-evm-survey/aurora-examples/hardhat/erc20/node_modules/node-fetch/lib/index.js:1454:13)
        at listOnTimeout (internal/timers.js:554:17)
        at processTimers (internal/timers.js:497:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [Makefile:4: deploy] Error 1
```

**Comment by bafu** [comment]
It seems to be a provider issue, and I can deploy the contract with the same command above now.

```
aurora-examples/hardhat/erc20 $ make deploy NETWORK=testnet_aurora
yarn hardhat run scripts/deploy.js --network testnet_aurora
yarn run v1.22.5
$ aurora-examples/hardhat/erc20/node_modules/.bin/hardhat run scripts/deploy.js --network testnet_aurora
Deploying contracts with the account: <my-wallet-address>
Account balance: 5891112980000000
WatermelonToken deployed to: <contract-address>
Done in 15.31s.
```
